services:
  projecteuler-js:
    image: projecteuler-js:latest
    build:
      context: .
      target: testing
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      - ./coverage:/app/coverage
    profiles: ["testing"]

  projecteuler-js-dev:
    image: projecteuler-js:dev
    build:
      context: .
      target: development
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      - ./:/app
    profiles: ["development"]
